version: '3.8'
services:
  web:
    build: .
    container_name: django_app
    env_file:
      - .env
    ports:
      - "8005:8005"
    volumes:
      - type: bind
        source: .
        target: /app